### ISSUE TITLE
README.md improvements

### ISSUE THREAD

**Issue by mxinden** [substrate-developer-hub/substrate-proof-of-existence#1]
As discussed with @shawntabrizi documenting  a couple of further action points needed in the README.md:

```markdown
1. Start your dev chain
    ```
    cd proof-of-existence
    ./build.sh # The repo doesn't contain a `build.sh` file.
    cargo build --release # As far as I can tell, the repo only contains a rust library, not a binary.
    ./target/release/proof-of-existence --dev
    ```

2. Start the `proof-of-existence-ui`

    ```
    cd proof-of-existence-ui
   # Maybe worth mentioning the NodeJS version here. As far as I could tell it is _11_.
   # Or how to run it in docker `docker run --rm -w $(pwd) --network host -v $(pwd):$(pwd) node:11 yarn install && yarn run dev`.
    yarn install
    yarn run dev
    ```
```

**Comment by shawntabrizi** [comment]
Fixed in the last couple of updates
